# Generated by Django 5.1.4 on 2026-05-08 23:22

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_seed_uom'),
        ('customers', '0002_fts_index'),
        ('sales', '0003_payment_refund_of'),
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=40)),
                ('fbr_credit_note_number', models.CharField(blank=True, max_length=40, null=True)),
                ('return_date', models.DateField()),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('wrong_item', 'Wrong item'), ('customer_changed_mind', 'Customer changed mind'), ('expired', 'Expired'), ('other', 'Other')], max_length=50)),
                ('reason_notes', models.TextField(blank=True, default='')),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('store_credit', 'Store credit'), ('card_reversal', 'Card reversal'), ('wallet_reversal', 'Wallet reversal'), ('bank_transfer', 'Bank transfer')], max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fbr_route', models.CharField(blank=True, choices=[('amend', 'Amend (within 72h)'), ('credit_note', 'Credit note (outside 72h)')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='customers.customer')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.terminal')),
            ],
            options={
                'db_table': 'returns',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('restocked', models.BooleanField(default=True)),
                ('movement_type', models.CharField(blank=True, default='', max_length=30)),
                ('original_sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_items', to='sales.saleitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('return_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'return_items',
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['tenant', '-return_date'], name='idx_returns_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['original_invoice'], name='idx_returns_orig'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.UniqueConstraint(fields=('tenant', 'return_number'), name='uniq_return_tenant_number'),
        ),
    ]
