# Generated by Django 5.1.4 on 2026-05-08 19:33

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0002_branch_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('audit_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='tenants.branch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'stock_audits',
            },
        ),
        migrations.CreateModel(
            name='StockAuditItem',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('counted_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=4, max_digits=14)),
                ('variance_reason', models.TextField(blank=True, default='')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockaudit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_audit_items',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='tenants.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_levels',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('purchase', 'Purchase'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out'), ('damage', 'Damage'), ('expiry', 'Expiry'), ('opening_balance', 'Opening balance')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('return', 'Return'), ('purchase_order', 'Purchase order'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('audit', 'Audit')], max_length=30, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productbatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.branch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='tenants.branch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='tenants.branch')),
            ],
            options={
                'db_table': 'stock_transfers',
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity_dispatched', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_transfer_items',
            },
        ),
        migrations.AddConstraint(
            model_name='stockaudit',
            constraint=models.UniqueConstraint(fields=('tenant', 'audit_number'), name='uniq_audit_tenant_number'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['branch'], name='idx_stock_branch'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'branch'), name='uniq_stocklevel_product_variant_branch'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='idx_movements_product'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', '-created_at'], name='idx_movements_branch_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_movements_reference'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('tenant', 'transfer_number'), name='uniq_transfer_tenant_number'),
        ),
    ]
