# Generated by Django 5.1.4 on 2026-06-14 09:00

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productbatch_supplier'),
        ('inventory', '0002_immutable_movements'),
        ('tenants', '0018_alter_tenant_vertical'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='uniq_stocklevel_product_variant_branch',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(condition=models.Q(('warehouse__isnull', False)), fields=['warehouse'], name='idx_stock_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(condition=models.Q(('warehouse__isnull', False)), fields=['warehouse', '-created_at'], name='idx_movements_warehouse_date'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('product', 'variant', 'branch'), name='uniq_stocklevel_pvb_no_wh'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('product', 'variant', 'warehouse'), name='uniq_stocklevel_pvw_wh'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['tenant'], name='idx_warehouses_tenant'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['branch'], name='idx_warehouses_branch'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uniq_warehouse_branch_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('branch',), name='uniq_warehouse_default_per_branch'),
        ),
    ]
