# Generated by Django 5.1.4 on 2026-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_backfill_di'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
