import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { LegalLayout } from "@/routes/legal";
import { SITE } from "@/lib/site";
import { useSeo } from "@/lib/useSeo";
export default function Privacy() {
    useSeo({
        title: "Privacy Policy",
        description: "How InvoiceSolution collects, uses and protects your data.",
        path: "/privacy",
    });
    return (_jsxs(LegalLayout, { title: "Privacy Policy", updated: "June 2026", children: [_jsxs("p", { children: ["This Privacy Policy explains how ", SITE.name, " (\u201Cwe\u201D, \u201Cus\u201D) collects, uses and protects information when you visit ", SITE.domain, " or use our services. By using our website or services, you agree to this policy."] }), _jsx("h2", { children: "Information we collect" }), _jsxs("ul", { children: [_jsx("li", { children: "Contact details you submit through our forms (name, business name, phone, email, city)." }), _jsx("li", { children: "Business information you share with us during onboarding." }), _jsx("li", { children: "Basic technical data such as your IP address and browser, used to keep the site secure." }), _jsx("li", { children: "For customers, the transaction and invoice data processed through our platform on your behalf." })] }), _jsx("h2", { children: "How we use information" }), _jsxs("ul", { children: [_jsx("li", { children: "To respond to your enquiries and provide demos and onboarding." }), _jsx("li", { children: "To deliver, maintain and improve our services." }), _jsx("li", { children: "To meet legal and tax obligations, including FBR record-retention requirements." }), _jsx("li", { children: "To communicate with you about your account and relevant updates." })] }), _jsx("h2", { children: "Data retention" }), _jsx("p", { children: "Invoice and transaction records are retained for the period required by Pakistani tax law (currently six years). Lead and contact information is kept only as long as needed to serve you, after which it is deleted or anonymised." }), _jsx("h2", { children: "Sharing" }), _jsx("p", { children: "We do not sell your data. We share information only where necessary to provide our services (for example, with FBR/PRAL to fiscalise invoices on your instruction) or where required by law." }), _jsx("h2", { children: "Security" }), _jsx("p", { children: "We apply industry-standard safeguards \u2014 encryption in transit, access controls and audit logging \u2014 to protect your information. No system is perfectly secure, but we work hard to keep yours safe." }), _jsx("h2", { children: "Your rights" }), _jsxs("p", { children: ["You can ask us to access, correct or delete your personal information at any time by emailing ", _jsx("a", { href: `mailto:${SITE.email}`, children: SITE.email }), "."] }), _jsx("h2", { children: "Contact" }), _jsxs("p", { children: ["Questions about this policy? Reach us at ", _jsx("a", { href: `mailto:${SITE.email}`, children: SITE.email }), "."] })] }));
}
