import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { LegalLayout } from "@/routes/legal";
import { SITE } from "@/lib/site";
import { useSeo } from "@/lib/useSeo";
export default function Terms() {
    useSeo({
        title: "Terms of Service",
        description: "The terms that govern your use of InvoiceSolution.",
        path: "/terms",
    });
    return (_jsxs(LegalLayout, { title: "Terms of Service", updated: "June 2026", children: [_jsxs("p", { children: ["These Terms of Service govern your use of ", SITE.name, " and the ", SITE.domain, " website. By using our services, you agree to these terms."] }), _jsx("h2", { children: "The service" }), _jsxs("p", { children: [SITE.name, " provides Point of Sale and Digital Invoicing software that integrates with FBR Digital Invoicing through a licensed integration. We are an independent software provider and are not a government body. While we work to keep invoices compliant, you remain responsible for the accuracy of the data you enter and for your own tax obligations."] }), _jsx("h2", { children: "Accounts" }), _jsxs("ul", { children: [_jsx("li", { children: "Accounts are provisioned by our team during onboarding." }), _jsx("li", { children: "You are responsible for keeping your login credentials secure." }), _jsx("li", { children: "You must provide accurate business and FBR information." })] }), _jsx("h2", { children: "Subscriptions & payment" }), _jsxs("ul", { children: [_jsx("li", { children: "Subscriptions are billed per the plan you choose (monthly or yearly), in PKR." }), _jsx("li", { children: "New accounts may include a trial period; details are confirmed at onboarding." }), _jsx("li", { children: "Fees charged directly by FBR/PRAL to your business are separate from our subscription." })] }), _jsx("h2", { children: "Acceptable use" }), _jsx("p", { children: "You agree not to misuse the service, attempt to disrupt it, or use it for any unlawful purpose. We may suspend access where these terms are breached." }), _jsx("h2", { children: "Availability" }), _jsx("p", { children: "We aim for high availability, and the POS terminal is designed to keep working offline. However, we do not guarantee uninterrupted service and are not liable for losses arising from downtime, third-party services, or events beyond our reasonable control." }), _jsx("h2", { children: "Limitation of liability" }), _jsx("p", { children: "To the maximum extent permitted by law, our liability is limited to the amount you paid for the service in the preceding three months. We are not liable for indirect or consequential losses." }), _jsx("h2", { children: "Changes" }), _jsx("p", { children: "We may update these terms from time to time. Continued use of the service after changes take effect constitutes acceptance of the updated terms." }), _jsx("h2", { children: "Contact" }), _jsxs("p", { children: ["Questions about these terms? Email ", _jsx("a", { href: `mailto:${SITE.email}`, children: SITE.email }), "."] })] }));
}
