# Generated by Django 5.1.4 on 2026-05-10 01:17

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_account_manager_tenant_internal_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Pakistan POS', help_text='Brand name shown on customer-facing surfaces.', max_length=100)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('default_trial_days', models.PositiveIntegerField(default=14)),
                ('payment_bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('payment_bank_account_title', models.CharField(blank=True, default='', max_length=255)),
                ('payment_bank_iban', models.CharField(blank=True, default='', max_length=50)),
                ('payment_jazzcash_business', models.CharField(blank=True, default='', max_length=20)),
                ('payment_easypaisa_business', models.CharField(blank=True, default='', max_length=20)),
                ('payment_raast_id', models.CharField(blank=True, default='', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Stable identifier (e.g. 'starter', 'pro', 'enterprise').", max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price_paisa', models.BigIntegerField(default=0)),
                ('yearly_price_paisa', models.BigIntegerField(default=0)),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('max_terminals', models.PositiveIntegerField(blank=True, null=True)),
                ('max_products', models.PositiveIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, help_text='Hide from new signups when false.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ('sort_order', 'monthly_price_paisa'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('next_invoice_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform_admin.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['status'], name='subscriptio_status_572d44_idx'), models.Index(fields=['next_invoice_at'], name='subscriptio_next_in_dd3aad_idx')],
            },
        ),
    ]
