# Generated by Django 5.1.4 on 2026-05-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_name',
            field=models.CharField(default='POS System', help_text='Brand name shown on customer-facing surfaces.', max_length=100),
        ),
    ]
