# Generated by Django 5.1.4 on 2026-06-30 08:12

import core.uuid7
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_remove_product_uniq_product_tenant_sku_and_more'),
        ('sales', '0007_alter_saleitem_sro_schedule_no'),
        ('tenants', '0021_alter_tenant_fbr_connection_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=40)),
                ('nightly_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('nightly_tax', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenants.branch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hotel_rooms',
                'ordering': ['display_order', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='GuestFolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('folio_number', models.CharField(max_length=40)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_cnic', models.CharField(max_length=20)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_address', models.TextField(blank=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('expected_check_out', models.DateTimeField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='tenants.branch')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_folios', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='hotel.room')),
            ],
            options={
                'db_table': 'hotel_guest_folios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('room', 'Room'), ('restaurant', 'Restaurant'), ('misc', 'Miscellaneous')], default='restaurant', max_length=15)),
                ('charge_date', models.DateField(default=datetime.date.today)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio_link', to='sales.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='hotel.guestfolio')),
            ],
            options={
                'db_table': 'hotel_folio_invoices',
                'ordering': ['charge_date', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'folio'], name='hotel_folio_tenant__5e9c93_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'branch'], name='hotel_rooms_tenant__9748ad_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='hotel_rooms_tenant__87a75a_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'branch', 'room_number'), name='uniq_room_tenant_branch_number'),
        ),
        migrations.AddIndex(
            model_name='guestfolio',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='hotel_guest_tenant__87152e_idx'),
        ),
        migrations.AddIndex(
            model_name='guestfolio',
            index=models.Index(fields=['tenant', 'status'], name='hotel_guest_tenant__00b54e_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestfolio',
            constraint=models.UniqueConstraint(fields=('tenant', 'folio_number'), name='uniq_folio_number_per_tenant'),
        ),
    ]
