# Generated by Django 5.1.4 on 2026-07-07 08:04

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('tenants', '0021_alter_tenant_fbr_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folioinvoice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_charges', to='hotel.room'),
        ),
        migrations.CreateModel(
            name='FolioRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('check_in', models.DateTimeField()),
                ('expected_check_out', models.DateTimeField(blank=True, null=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_booked', to='hotel.guestfolio')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folio_rooms', to='hotel.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hotel_folio_rooms',
                'indexes': [models.Index(fields=['tenant', 'folio'], name='hotel_folio_tenant__70896f_idx')],
                'constraints': [models.UniqueConstraint(fields=('folio', 'room'), name='uniq_folioroom_folio_room')],
            },
        ),
    ]
