# Generated by Django 5.1.4 on 2026-07-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_folioinvoice_room_folioroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestfolio',
            name='partner_cnic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guestfolio',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
