# Generated by Django 5.1.4 on 2026-05-08 21:55

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_cashsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to='tenants.terminal')),
            ],
            options={
                'db_table': 'sync_log',
                'indexes': [models.Index(fields=['terminal', '-received_at'], name='idx_sync_log_terminal'), models.Index(condition=models.Q(('status', 'failed')), fields=['tenant'], name='idx_sync_log_failed')],
            },
        ),
    ]
