# Generated by Django 5.1.4 on 2026-05-08 22:20

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_invoice_is_annexure_c_linked'),
        ('tenants', '0003_cashsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbrCancelBudget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('month_start', models.DateField()),
                ('previous_month_sales', models.DecimalField(decimal_places=4, max_digits=14)),
                ('budget_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('consumed_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('last_recalculated_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fbr_cancel_budget',
            },
        ),
        migrations.CreateModel(
            name='FbrCancelBudgetConsumption',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('consumption_type', models.CharField(choices=[('edit', 'Edit'), ('cancel', 'Cancel')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='fbr.fbrcancelbudget')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancel_budget_consumptions', to='sales.invoice')),
            ],
            options={
                'db_table': 'fbr_cancel_budget_consumption',
            },
        ),
        migrations.CreateModel(
            name='FbrIpWhitelist',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('hosting_provider', models.CharField(blank=True, default='', max_length=100)),
                ('hosting_country', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbr_ip_whitelist_entries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fbr_ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name='FbrScenarioTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('scenario_code', models.CharField(max_length=10)),
                ('scenario_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitting', 'Submitting'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fbr_invoice_number', models.CharField(blank=True, max_length=40, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fbr_scenario_tests',
            },
        ),
        migrations.CreateModel(
            name='FbrSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('return_ref', models.UUIDField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('endpoint', models.CharField(choices=[('postinvoicedata', 'postinvoicedata'), ('validateinvoicedata', 'validateinvoicedata'), ('editinvoice', 'editinvoice'), ('cancelinvoice', 'cancelinvoice')], max_length=100)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=20, null=True)),
                ('fbr_invoice_number', models.CharField(blank=True, max_length=40, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbr_submissions', to='sales.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fbr_submissions',
            },
        ),
        migrations.CreateModel(
            name='FbrToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('licensed_integrator', models.CharField(default='PRAL', max_length=50)),
                ('token_encrypted', models.TextField(db_column='token_encrypted')),
                ('api_endpoint', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'fbr_tokens',
            },
        ),
        migrations.AddConstraint(
            model_name='fbrcancelbudget',
            constraint=models.UniqueConstraint(fields=('tenant', 'month_start'), name='uniq_fbr_budget_tenant_month'),
        ),
        migrations.AddIndex(
            model_name='fbrcancelbudgetconsumption',
            index=models.Index(fields=['budget'], name='idx_consumption_budget'),
        ),
        migrations.AddConstraint(
            model_name='fbrscenariotest',
            constraint=models.UniqueConstraint(fields=('tenant', 'scenario_code'), name='uniq_fbr_scenario_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='fbrsubmission',
            index=models.Index(fields=['invoice', '-submitted_at'], name='idx_fbr_submissions_invoice'),
        ),
        migrations.AddIndex(
            model_name='fbrsubmission',
            index=models.Index(condition=models.Q(('status_code', '00'), _negated=True), fields=['tenant', '-submitted_at'], name='idx_fbr_subs_failed'),
        ),
        migrations.AddConstraint(
            model_name='fbrtoken',
            constraint=models.UniqueConstraint(fields=('tenant', 'environment'), name='uniq_fbr_token_tenant_env'),
        ),
    ]
