# Generated by Django 5.1.4 on 2026-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr', '0002_immutability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbrscenariotest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitting', 'Submitting'), ('success', 'Success'), ('failed', 'Failed'), ('not_implemented', 'Not yet supported')], default='pending', max_length=20),
        ),
    ]
