# Generated by Django 5.1.4 on 2026-05-28 15:56

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr', '0003_alter_fbrscenariotest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioPayloadTemplate',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scenario_code', models.CharField(max_length=10)),
                ('payload', models.JSONField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenario_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fbr_scenario_payload_templates',
                'indexes': [models.Index(fields=['scenario_code'], name='fbr_scenari_scenari_cd1bd3_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'scenario_code'), name='uniq_scenario_template_name_code')],
            },
        ),
    ]
