# Generated by Django 5.1.4 on 2026-05-30 14:59

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr', '0004_scenariopayloadtemplate'),
        ('tenants', '0013_branch_fbr_pos_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchFbrToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20)),
                ('licensed_integrator', models.CharField(default='PRAL', max_length=50)),
                ('token_encrypted', models.TextField(db_column='token_encrypted')),
                ('api_endpoint', models.TextField(default='https://gw.fbr.gov.pk')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbr_tokens', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'branch_fbr_tokens',
                'constraints': [models.UniqueConstraint(fields=('branch', 'environment'), name='uniq_branch_fbr_token_branch_env')],
            },
        ),
    ]
