# Generated by Django 5.1.4 on 2026-09-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbr', '0005_branchfbrtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbrscenariotest',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
