# Generated by Django 5.1.4 on 2026-05-08 19:33

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_branch_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HsCode',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('default_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'hs_codes',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=50)),
                ('name_ur', models.CharField(blank=True, default='', max_length=50)),
                ('is_decimal_quantity', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'units_of_measure',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ur', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ur', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('min_sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('is_serialized', models.BooleanField(default=False)),
                ('is_batch_tracked', models.BooleanField(default=False)),
                ('is_weighable', models.BooleanField(default=False)),
                ('has_variants', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('hs_code', models.ForeignKey(blank=True, db_column='hs_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.hscode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('initial_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('current_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='tenants.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.product')),
            ],
            options={
                'db_table': 'product_batches',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_compound', models.BooleanField(default=False)),
                ('applies_to', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('both', 'Both')], default='goods', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tax_rates',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.taxrate'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(db_column='uom_code', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='uom_default',
            field=models.ForeignKey(blank=True, db_column='uom_default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_codes', to='catalog.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['tenant'], name='idx_categories_tenant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_categories_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_category_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number', 'branch'), name='uniq_batch_product_batchno_branch'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'sku'), name='uniq_variant_product_sku'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tenant'], name='idx_tax_rates_tenant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=['tenant'], name='idx_products_tenant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('barcode__isnull', False)), fields=['tenant', 'barcode'], name='idx_products_barcode'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_products_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='uniq_product_tenant_sku'),
        ),
        migrations.AddIndex(
            model_name='hscode',
            index=models.Index(fields=['parent_code'], name='idx_hs_codes_parent'),
        ),
    ]
