# Generated by Django 5.1.4 on 2026-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_third_schedule',
            field=models.BooleanField(default=False, help_text="Tick if this product is on Pakistan's 3rd Schedule (taxed on retail price, not sale price). Common 3rd-Schedule items: sugar, biscuits, carbonated drinks, cigarettes, mobile phones, tea. retail_price must be set when this is on."),
        ),
    ]
