# Generated by Django 5.1.4 on 2026-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productbatch_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(default='Goods at standard rate (default)', help_text="How FBR taxes this item (Standard, 3rd Schedule, Reduced, Zero-rated, Exempt, Electric Vehicle, …). Must match PRAL's transtypecode list exactly; pick from the dropdown.", max_length=50),
        ),
    ]
