# Generated by Django 5.1.4 on 2026-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sro_item_serial_no',
            field=models.CharField(blank=True, default='', help_text="The item's serial number within that SRO schedule, e.g. 70.", max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sro_schedule_no',
            field=models.CharField(blank=True, default='', help_text='FBR SRO schedule, e.g. "EIGHTH SCHEDULE Table 1". Needed for reduced-rate goods.', max_length=50),
        ),
    ]
