# Generated by Django 5.1.4 on 2026-06-16 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_sro_item_serial_no_product_sro_schedule_no'),
        ('tenants', '0019_enable_warehouses_for_di'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_tenant_sku',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'sku'), name='uniq_product_tenant_sku'),
        ),
    ]
