"""PDF export via reportlab — a professionally branded report document.

Layout: a coloured header band (tenant logo + business name + NTN), the report
title + filter subtitle + generated-at line as clear heads, then the data table
(brand-coloured header, right-aligned numbers, zebra rows, bold totals), and a
page footer (generated-by + page number). ReportLab paginates automatically and
repeats the table header on each page.

reportlab (not WeasyPrint) is used deliberately: no native deps (cairo/pango),
so the docker image stays small.
"""

from __future__ import annotations

import io
from decimal import Decimal
from pathlib import Path

from django.http import HttpResponse
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from ..base import ReportResult

# TDCP / brand green — matches the invoice PDF + the resort's logo.
BRAND = HexColor("#0a6d46")
BRAND_DARK = HexColor("#075034")
INK = HexColor("#0f172a")
MUTED = HexColor("#64748b")
LINE = HexColor("#E5E7EB")
ZEBRA = HexColor("#F5F8F6")


def _format(value, kind: str) -> str:
    if value is None:
        return ""
    if kind == "money":
        d = value if isinstance(value, Decimal) else Decimal(str(value))
        return f"Rs. {d:,.2f}"
    if kind == "percent":
        d = value if isinstance(value, Decimal) else Decimal(str(value))
        return f"{d:.2f}%"
    return str(value)


def _logo_image(logo_path, *, height_mm: float = 14):
    """Load the tenant logo (square-ish PNG) for the header, or None if absent."""
    if not logo_path:
        return None
    p = Path(logo_path)
    if not p.exists():
        return None
    try:
        # Keep aspect ratio: the TDCP mark is ~square, render at a fixed height.
        img = Image(str(p), width=height_mm * mm, height=height_mm * mm)
        img.hAlign = "LEFT"
        return img
    except Exception:
        return None


def pdf_response(
    result: ReportResult, *,
    filename: str, title: str,
    tenant_business_name: str, tenant_ntn: str,
    subtitle: str = "",
    logo_path: str | None = None,
) -> HttpResponse:
    buf = io.BytesIO()
    # 12-hour clock with AM/PM (e.g. "04 Sep 2026, 3:52 PM"), leading zero on the
    # hour stripped for a natural read.
    generated = timezone.localtime(timezone.now()).strftime("%d %b %Y, %I:%M %p").replace(", 0", ", ")

    def _decorate(canvas, doc):
        """Header accent + footer drawn on every page."""
        w, h = landscape(A4)
        canvas.saveState()
        canvas.setFillColor(BRAND)
        canvas.rect(0, h - 6, w, 6, stroke=0, fill=1)  # thin top accent bar
        canvas.restoreState()
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(MUTED)
        canvas.drawString(12 * mm, 8 * mm, "Generated by invoicesolution.pk")
        canvas.drawRightString(w - 12 * mm, 8 * mm, f"Page {doc.page}")
        canvas.setStrokeColor(LINE)
        canvas.setLineWidth(0.4)
        canvas.line(12 * mm, 11 * mm, w - 12 * mm, 11 * mm)
        canvas.restoreState()

    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=14 * mm, bottomMargin=16 * mm,
        title=title, author=tenant_business_name,
    )
    styles = getSampleStyleSheet()
    biz = ParagraphStyle("biz", parent=styles["Normal"], fontName="Helvetica-Bold",
                         fontSize=15, leading=18, textColor=BRAND_DARK)
    meta = ParagraphStyle("meta", parent=styles["Normal"], fontSize=8,
                          leading=11, textColor=MUTED)
    rtitle = ParagraphStyle("rtitle", parent=styles["Normal"], fontName="Helvetica-Bold",
                            fontSize=12, leading=15, textColor=INK, spaceBefore=2)
    rsub = ParagraphStyle("rsub", parent=styles["Normal"], fontSize=8.5,
                          leading=11, textColor=MUTED)

    story = []

    # ---- Branded header: logo (left) + tenant identity ----
    logo = _logo_image(logo_path, height_mm=14)
    ident = [
        Paragraph(tenant_business_name, biz),
        Paragraph(f"NTN {tenant_ntn}", meta),
    ]
    if logo is not None:
        head = Table([[logo, ident]], colWidths=[18 * mm, None])
        head.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (0, 0), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        story.append(head)
    else:
        for p in ident:
            story.append(p)
    story.append(Spacer(1, 8))

    # ---- Report heads: title · subtitle · generated line ----
    story.append(Paragraph(title, rtitle))
    if subtitle:
        story.append(Paragraph(subtitle, rsub))
    story.append(Paragraph(f"Generated {generated}", rsub))
    story.append(Spacer(1, 6))

    # ---- Data table ----
    header_row = [c.label for c in result.columns]
    body = [
        [_format(row.get(c.key), c.kind) for c in result.columns]
        for row in result.rows
    ]
    table_data = (
        [header_row] + body if body
        else [header_row, ["(no rows)"] + [""] * (len(header_row) - 1)]
    )

    totals_row_idx = None
    if result.totals:
        totals_cells = []
        for i, c in enumerate(result.columns):
            if c.key in result.totals:
                totals_cells.append(_format(result.totals[c.key], c.kind))
            elif i == 0:
                totals_cells.append("TOTAL")
            else:
                totals_cells.append("")
        table_data.append(totals_cells)
        totals_row_idx = len(table_data) - 1

    # Table spans the FULL content width (A4 minus the page margins) and is
    # LEFT-aligned so its left edge lines up with the logo/header. Column widths
    # are distributed proportionally to each column's widest cell, then scaled so
    # they sum to exactly doc.width (a true 100%-width table, not a narrow
    # centered one).
    def _col_weight(ci: int) -> float:
        longest = len(str(header_row[ci]))
        for r in table_data[1:]:
            if ci < len(r):
                longest = max(longest, len(str(r[ci])))
        return max(4.0, float(longest))  # floor so tiny columns aren't hairline-thin

    weights = [_col_weight(ci) for ci in range(len(header_row))]
    total_w = sum(weights) or 1.0
    col_widths = [doc.width * (w / total_w) for w in weights]

    table = Table(table_data, colWidths=col_widths, repeatRows=1, hAlign="LEFT")
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, BRAND_DARK),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ZEBRA]),
        ("LINEBELOW", (0, 1), (-1, -1), 0.25, LINE),
    ]
    # Right-align numeric columns (money / decimal / int / percent) for scannability.
    for ci, c in enumerate(result.columns):
        if c.kind in ("money", "decimal", "int", "percent"):
            style.append(("ALIGN", (ci, 0), (ci, -1), "RIGHT"))
    if totals_row_idx is not None:
        style += [
            ("BACKGROUND", (0, totals_row_idx), (-1, totals_row_idx), ZEBRA),
            ("FONTNAME", (0, totals_row_idx), (-1, totals_row_idx), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, totals_row_idx), (-1, totals_row_idx), BRAND_DARK),
            ("LINEABOVE", (0, totals_row_idx), (-1, totals_row_idx), 0.75, BRAND),
        ]
    table.setStyle(TableStyle(style))
    story.append(table)

    doc.build(story, onFirstPage=_decorate, onLaterPages=_decorate)
    buf.seek(0)

    response = HttpResponse(buf.read(), content_type="application/pdf")
    response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response
