# Generated by Django 5.1.4 on 2026-05-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_staff',
            field=models.BooleanField(default=False, help_text='Works for the SaaS operator (us), not a tenant.'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super admin'), ('billing_admin', 'Billing admin'), ('support_lead', 'Support lead'), ('support_agent', 'Support agent'), ('sales_lead', 'Sales lead'), ('sales_rep', 'Sales rep'), ('read_only_observer', 'Read-only observer')], default='', help_text='Empty for tenant users; set when is_platform_staff=true.', max_length=30),
        ),
    ]
