# Generated by Django 5.1.4 on 2026-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_platform_staff_user_platform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super admin'), ('account_manager', 'Account manager'), ('billing_admin', 'Billing admin'), ('support_lead', 'Support lead'), ('support_agent', 'Support agent'), ('sales_lead', 'Sales lead'), ('sales_rep', 'Sales rep'), ('read_only_observer', 'Read-only observer')], default='', help_text='Empty for tenant users; set when is_platform_staff=true.', max_length=30),
        ),
    ]
