# Generated by Django 5.1.4 on 2026-06-08 19:23

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_productbatch_supplier'),
        ('tenants', '0018_alter_tenant_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('min_select', models.PositiveSmallIntegerField(default=0)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_modifier_groups',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant.modifiergroup')),
            ],
            options={
                'db_table': 'restaurant_modifiers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_links', to='catalog.product')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='restaurant.modifiergroup')),
            ],
            options={
                'db_table': 'restaurant_menu_item_modifier_groups',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'restaurant_tables',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='modifiergroup',
            index=models.Index(fields=['tenant'], name='restaurant__tenant__17671a_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitemmodifiergroup',
            constraint=models.UniqueConstraint(fields=('product', 'group'), name='uniq_menuitem_group'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['tenant', 'branch'], name='restaurant__tenant__d48d04_idx'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'branch', 'name'), name='uniq_table_tenant_branch_name'),
        ),
    ]
