# Generated by Django 5.1.4 on 2026-06-20 14:11

import core.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('business_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('business_type', models.CharField(blank=True, max_length=80)),
                ('product_interest', models.CharField(blank=True, choices=[('pos', 'POS Terminal'), ('digital_invoicing', 'Digital Invoicing'), ('both', 'Both'), ('', 'Unspecified')], default='', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='website', max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('handled', models.BooleanField(default=False, help_text='Tick once a team member has followed up.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='idx_lead_created'), models.Index(fields=['handled'], name='idx_lead_handled')],
            },
        ),
    ]
