import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * A stylised FBR receipt rendered in pure markup (no image asset) so it stays
 * crisp at any size and matches the brand. Used as the hero visual.
 */
export function ReceiptMock() {
    return (_jsxs("div", { className: "relative rounded-2xl border border-slate-100 bg-white p-3 shadow-card", children: [_jsxs("div", { className: "mb-3 flex items-center gap-1.5 px-1", children: [_jsx("span", { className: "h-2.5 w-2.5 rounded-full bg-slate-200" }), _jsx("span", { className: "h-2.5 w-2.5 rounded-full bg-slate-200" }), _jsx("span", { className: "h-2.5 w-2.5 rounded-full bg-slate-200" }), _jsx("span", { className: "ml-2 h-4 flex-1 rounded bg-slate-100" })] }), _jsxs("div", { className: "grid gap-3 sm:grid-cols-[1.3fr_1fr]", children: [_jsxs("div", { className: "rounded-xl bg-slate-50 p-4", children: [_jsxs("div", { className: "mb-3 flex items-center justify-between", children: [_jsx("span", { className: "text-sm font-semibold text-ink", children: "Checkout" }), _jsx("span", { className: "rounded-full bg-brand-50 px-2 py-0.5 text-[11px] font-semibold text-brand-700", children: "Terminal 1" })] }), _jsx("ul", { className: "space-y-2.5", children: [
                                    ["Tapal Danedar 950g", "Rs 1,250.00"],
                                    ["Surf Excel 1kg", "Rs 740.00"],
                                    ["Nestlé Milk Pack ×6", "Rs 1,140.00"],
                                ].map(([name, price]) => (_jsxs("li", { className: "flex items-center justify-between text-[13px]", children: [_jsx("span", { className: "text-ink-soft", children: name }), _jsx("span", { className: "font-mono text-ink", children: price })] }, name))) }), _jsx("div", { className: "my-3 border-t border-dashed border-slate-200" }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm font-semibold text-ink", children: "Total" }), _jsx("span", { className: "font-mono text-base font-bold text-ink", children: "Rs 3,130.00" })] }), _jsx("div", { className: "mt-3 grid grid-cols-3 gap-1.5", children: ["Cash", "Card", "Raast"].map((m, i) => (_jsx("div", { className: `rounded-lg px-2 py-1.5 text-center text-[11px] font-medium ${i === 0 ? "bg-brand-600 text-white" : "bg-white text-ink-muted ring-1 ring-slate-200"}`, children: m }, m))) })] }), _jsxs("div", { className: "rounded-xl border border-slate-100 bg-white p-4", children: [_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-[11px] font-bold uppercase tracking-wide text-ink", children: "Tax Invoice" }), _jsx("div", { className: "mt-0.5 text-[10px] text-ink-muted", children: "FBR Digital Invoicing" })] }), _jsx("div", { className: "my-3 flex justify-center", children: _jsx("div", { className: "grid grid-cols-7 gap-0.5 rounded-lg bg-white p-2 ring-1 ring-slate-200", children: Array.from({ length: 49 }).map((_, i) => {
                                        const on = [0, 1, 2, 6, 7, 8, 12, 13, 14, 16, 18, 22, 24, 28, 30, 31, 33, 36, 40, 41, 42, 44, 46, 48].includes(i);
                                        return (_jsx("span", { className: `h-1.5 w-1.5 rounded-[1px] ${on ? "bg-ink" : "bg-transparent"}` }, i));
                                    }) }) }), _jsxs("div", { className: "space-y-1 text-center", children: [_jsx("div", { className: "text-[10px] text-ink-muted", children: "FBR Invoice No." }), _jsx("div", { className: "font-mono text-[11px] font-semibold text-ink", children: "7000007DI1-...4290" }), _jsx("div", { className: "mt-2 inline-flex items-center gap-1 rounded-full bg-brand-50 px-2.5 py-1 text-[10px] font-bold text-brand-700", children: "\u2713 FBR VALIDATED" })] })] })] })] }));
}
