# Generated by Django 5.1.4 on 2026-05-08 21:17

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_cashsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customer_groups',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('ntn', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_type', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered')], default='unregistered', max_length=20)),
                ('province', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('store_credit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customergroup')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('opening', 'Opening')], max_length=30)),
                ('reference_type', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('running_balance', models.DecimalField(decimal_places=4, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customer_ledger',
            },
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_customer_group_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['tenant'], name='idx_customers_tenant'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('phone__isnull', False)), fields=['tenant', 'phone'], name='idx_customers_phone'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['customer', '-created_at'], name='idx_ledger_customer_date'),
        ),
    ]
