# Generated by Django 5.1.4 on 2026-05-08 18:22

import core.uuid7
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pgcrypto powers gen_random_uuid(), used as the Postgres-side default
        # for direct SQL inserts. Python ORM inserts go through core.uuid7.uuid7
        # (UUID v7); both flavours satisfy UNIQUE.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pgcrypto;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('ntn', models.CharField(max_length=20, unique=True)),
                ('strn', models.CharField(blank=True, max_length=20, null=True)),
                ('cnic_owner', models.CharField(blank=True, max_length=15, null=True)),
                ('business_type', models.CharField(choices=[('sole_proprietor', 'Sole Proprietor'), ('partnership', 'Partnership'), ('private_ltd', 'Private Limited'), ('public_ltd', 'Public Limited'), ('aop', 'Association of Persons')], max_length=50)),
                ('fbr_business_natures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('fbr_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(choices=[('PUNJAB', 'Punjab'), ('SINDH', 'Sindh'), ('KP', 'Khyber Pakhtunkhwa'), ('BALOCHISTAN', 'Balochistan'), ('ICT', 'Islamabad Capital Territory'), ('GB', 'Gilgit-Baltistan'), ('AJK', 'Azad Jammu & Kashmir')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('subscription_plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=50)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('accountant', 'Accountant'), ('auditor', 'Auditor')], max_length=30)),
                ('branch_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_permissions', models.JSONField(blank=True, default=dict)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_memberships',
                'indexes': [models.Index(fields=['user'], name='idx_memberships_user'), models.Index(condition=models.Q(('is_active', True)), fields=['tenant'], name='idx_memberships_tenant_active')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_tenant_user_membership')],
            },
        ),
    ]
