# Generated by Django 5.1.4 on 2026-05-08 19:33

import core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('PUNJAB', 'Punjab'), ('SINDH', 'Sindh'), ('KP', 'Khyber Pakhtunkhwa'), ('BALOCHISTAN', 'Balochistan'), ('ICT', 'Islamabad Capital Territory'), ('GB', 'Gilgit-Baltistan'), ('AJK', 'Azad Jammu & Kashmir')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('fbr_pos_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_header', models.TextField(blank=True, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.tenant')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device_fingerprint', models.CharField(max_length=128, unique=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
                ('printer_config', models.JSONField(blank=True, default=dict)),
                ('scanner_config', models.JSONField(blank=True, default=dict)),
                ('drawer_config', models.JSONField(blank=True, default=dict)),
                ('customer_display_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'terminals',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['tenant'], name='idx_branches_tenant'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_branch_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['branch'], name='idx_terminals_branch'),
        ),
    ]
