# Generated by Django 5.1.4 on 2026-05-08 21:17

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_branch_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField()),
                ('opened_with_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_with_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('variance_reason', models.TextField(blank=True, default='')),
                ('total_sales', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_returns', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cash_in', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cash_out', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='tenants.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='tenants.tenant')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='tenants.terminal')),
            ],
            options={
                'db_table': 'cash_sessions',
                'indexes': [models.Index(condition=models.Q(('status', 'open')), fields=['terminal'], name='idx_cash_sessions_term_open'), models.Index(fields=['tenant', '-opened_at'], name='idx_cash_sessions_tenant_date')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('terminal',), name='uniq_open_session_per_terminal')],
            },
        ),
    ]
