# Generated by Django 5.1.4 on 2026-05-08 22:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_cashsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='tenants.tenant')),
                ('enabled_payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('easypaisa_merchant_id', models.CharField(blank=True, default='', max_length=50)),
                ('easypaisa_qr_url', models.TextField(blank=True, default='')),
                ('jazzcash_merchant_id', models.CharField(blank=True, default='', max_length=50)),
                ('jazzcash_qr_url', models.TextField(blank=True, default='')),
                ('raast_iban', models.CharField(blank=True, default='', max_length=34)),
                ('raast_qr_url', models.TextField(blank=True, default='')),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_iban', models.CharField(blank=True, default='', max_length=34)),
                ('bank_account_bank', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
    ]
