# Generated by Django 5.1.4 on 2026-05-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
