# Generated by Django 5.1.4 on 2026-05-10 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_onboarding_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account_manager',
            field=models.ForeignKey(blank=True, help_text='Platform staff member responsible for this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Platform-team-only notes about this tenant.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='signup_source',
            field=models.CharField(blank=True, default='', help_text='How did this tenant arrive? e.g. self_serve, sales, reseller, partner_referral.', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Free-form list of tags (e.g. ['vip', 'cash-only'])."),
        ),
    ]
