# Generated by Django 5.1.4 on 2026-05-10 18:54

import apps.tenants.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_modules_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='modules_enabled',
            field=models.JSONField(blank=True, default=apps.tenants.modules.default_modules_enabled, help_text="Module keys this tenant is allowed to use. Forced modules (sales, fbr) are always enabled. Edit via the 'Modules enabled' widget on the change form."),
        ),
    ]
