# Generated by Django 5.1.4 on 2026-05-19 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenant_modules_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_mode',
            field=models.CharField(choices=[('pos', 'POS — counter-side terminal'), ('digital_invoicing', 'Digital Invoicing only — back-office'), ('both', 'Both POS and Digital Invoicing')], default='digital_invoicing', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='fbr_business_natures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Importer', 'Importer'), ('Exporter', 'Exporter'), ('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('Retailer', 'Retailer'), ('Service Provider', 'Service Provider'), ('Other', 'Other')], max_length=50), blank=True, default=list, help_text='One or more FBR-defined business natures. Required before submitting invoices to PRAL.', size=None),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='fbr_sector',
            field=models.CharField(blank=True, choices=[('Potassium Chlorate', 'Potassium Chlorate'), ('Cement or Concrete Blocks', 'Cement or Concrete Blocks'), ('Mobile', 'Mobile'), ('Wholesale / Retails', 'Wholesale / Retails'), ('Pharmaceuticals', 'Pharmaceuticals'), ('CNG Stations', 'CNG Stations'), ('Automobile', 'Automobile'), ('Services', 'Services'), ('Gas Distribution', 'Gas Distribution'), ('Electricity Distribution', 'Electricity Distribution'), ('Petroleum', 'Petroleum'), ('Telecom', 'Telecom'), ('Textile', 'Textile'), ('FMCG', 'FMCG'), ('Steel', 'Steel'), ('All Other Sectors', 'All Other Sectors')], help_text='The single FBR-defined sector this tenant operates in. Drives the scenarioId list for sandbox testing.', max_length=50, null=True),
        ),
    ]
