# Generated by Django 5.1.4 on 2026-05-25 06:00

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_platform_staff_user_platform_role'),
        ('tenants', '0009_tenant_business_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashiers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
