# Generated by Django 5.1.4 on 2026-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='assigned_scenarios',
            field=models.JSONField(blank=True, default=list, help_text="The FBR scenarios assigned to this tenant in IRIS. Paste from the tenant's IRIS profile. When set, this list determines which scenarios the runner tests (overrides our manual-derived nature×sector default)."),
        ),
    ]
