# Generated by Django 5.1.4 on 2026-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_assigned_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fbr_test_buyer_ntn',
            field=models.CharField(blank=True, default='', help_text="NTN of a real registered buyer for sandbox SN001/SN005 tests. PRAL's docs default (1000000000007) is not actually registered — arrange a real NTN with a partner business. Leave empty if no registered-buyer scenarios are assigned.", max_length=20),
        ),
    ]
