# Generated by Django 5.1.4 on 2026-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_fbr_test_buyer_ntn'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fbr_pos_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
