# Generated by Django 5.1.4 on 2026-05-30 15:21

from django.db import migrations, models


def backfill_terminal_index(apps, schema_editor):
    """Assign each existing terminal a stable per-branch ordinal (1, 2, …)
    in creation order, so legacy terminals get collision-free invoice numbers
    before the unique constraint is enforced."""
    Terminal = apps.get_model("tenants", "Terminal")
    from collections import defaultdict

    counters = defaultdict(int)
    # Deterministic order: oldest first per branch.
    for t in Terminal.objects.order_by("branch_id", "created_at", "id").iterator():
        if t.terminal_index is not None:
            continue
        counters[t.branch_id] += 1
        t.terminal_index = counters[t.branch_id]
        t.save(update_fields=["terminal_index"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_branch_fbr_pos_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='terminal_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_terminal_index, noop_reverse),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(condition=models.Q(('terminal_index__isnull', False)), fields=('branch', 'terminal_index'), name='uniq_terminal_branch_index'),
        ),
    ]
