# Generated by Django 5.1.4 on 2026-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_terminal_terminal_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='paired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='pairing_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='pairing_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
