# Generated by Django 5.1.4 on 2026-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_terminal_paired_at_terminal_pairing_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fbr_connection_type',
            field=models.CharField(choices=[('di_api', 'Direct DI-API (PRAL Bearer token + scenarios)'), ('ims_sdc', 'IMS / SDC Fiscalization service (POS ID, no token, no scenarios)')], default='di_api', max_length=10),
        ),
    ]
