# Generated by Django 5.1.4 on 2026-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_fbr_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='vertical',
            field=models.CharField(choices=[('grocery', 'Grocery / general retail'), ('pharmacy', 'Pharmacy')], default='grocery', max_length=20),
        ),
    ]
