# Generated by Django 5.1.4 on 2026-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenant_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='vertical',
            field=models.CharField(choices=[('grocery', 'Grocery / general retail'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant / F&B')], default='grocery', max_length=20),
        ),
    ]
