# Generated by Django 5.1.4 on 2026-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_alter_tenant_fbr_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='fbr_connection_type',
            field=models.CharField(choices=[('di_api', 'Direct DI-API (PRAL Bearer token + scenarios)'), ('ims_sdc', 'IMS / SDC Fiscalization service (POS ID, no token, no scenarios)'), ('pra_cloud', 'PRA Cloud IMS (POS ID + Bearer token, no local component)'), ('none', 'Non-fiscal (no FBR / no tax-authority validation)')], default='di_api', max_length=10),
        ),
    ]
