# Generated by Django 5.1.4 on 2026-07-23 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_alter_tenant_fbr_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='services_tax_rate_card',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reduced services sales-tax % for FULLY-card payments (PRA card rate, e.g. 8.00). Leave blank to disable the auto-swap.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='services_tax_rate_standard',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Standard services sales-tax % (cash / non-card payments).', max_digits=5),
        ),
    ]
