# Generated by Django 5.1.4 on 2026-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_tenant_services_tax_rate_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='is_order_taking_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('accountant', 'Accountant'), ('auditor', 'Auditor')], max_length=30),
        ),
    ]
