# Generated by Django 5.1.4 on 2026-05-09 00:11

import core.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_seed_uom'),
        ('tenants', '0004_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gross', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('net', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('refund_count', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_built_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='reports_dai_tenant__b6ce5f_idx'), models.Index(fields=['tenant', 'branch', 'date'], name='reports_dai_tenant__9e41d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'date'), name='dailysales_uniq_per_branch_day')],
            },
        ),
        migrations.CreateModel(
            name='ProductVelocity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_built_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'date'], name='reports_pro_tenant__fc4750_idx'), models.Index(fields=['tenant', 'product', 'date'], name='reports_pro_tenant__73e2d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'branch', 'date'), name='velocity_uniq_per_product_branch_day')],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('filters_json', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user', 'report_name'], name='reports_rep_tenant__15a133_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'report_name', 'label'), name='report_favorite_unique_label')],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=core.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=64)),
                ('filters_json', models.JSONField(default=dict)),
                ('export_format', models.CharField(blank=True, choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('pdf', 'pdf')], default='', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('output_path', models.CharField(blank=True, default='', max_length=512)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user', '-created_at'], name='reports_rep_tenant__0cf29a_idx'), models.Index(fields=['tenant', 'status'], name='reports_rep_tenant__9a2b4b_idx')],
            },
        ),
    ]
