# Generated by Django 5.1.4 on 2026-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvelocity',
            name='net_revenue',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
