# Generated by Django 5.1.4 on 2026-05-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_annexure_c_linked',
            field=models.BooleanField(default=False),
        ),
    ]
