# Generated by Django 5.1.4 on 2026-05-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_is_annexure_c_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='sales.payment'),
        ),
    ]
