# Generated by Django 5.1.4 on 2026-06-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('sales', '0004_invoice_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='covers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kitchen_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('sent_to_kitchen', 'Sent to kitchen'), ('ready', 'Ready'), ('served', 'Served')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_type',
            field=models.CharField(blank=True, choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.table'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sent_to_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
