# Generated by Django 5.1.4 on 2026-06-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_and_more'),
        ('sales', '0005_invoice_covers_invoice_kitchen_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.warehouse'),
        ),
    ]
