# Generated by Django 5.1.4 on 2026-06-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoice_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='sro_schedule_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
