# Generated by Django 5.1.4 on 2026-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleitem_sro_schedule_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kitchen_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='kot_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
